### ISSUE TITLE
In exported synths, Deep Zoom Collection's root is given extension dsc rather than dzc

### ISSUE THREAD

**Issue by natelawrence** [dddExperiments/PhotosynthDownloader#1]
In exported synths, the Deep Zoom Collection's root is given extension **dsc** rather than **dzc**.

**Comment by dddExperiments** [comment]
**I'm on the fence**. It's an easy change but then it will break compatibility for previously downloaded synth.
Thus I would have to fix the viewer to first try to download dzc and then redirect to dsc if it's not found.
It seems more trouble than having a typo. The only consumer of this zip archive is the offlineviewer anyway so IMO it doesn't really matter that there is a typo in file extension? FYI the zip archive is not a direct zip of what is store in the cloud as images are served from different sub domains. Thus I've grouped all images in an "images" folder and all point cloud bin files in a "points" folder. Any ps1 viewer would have to match the way I'm saving data in the zip folder to fetch data properly (thus it seems ok to keep typo).

**Comment by natelawrence** [comment]
I understand that it's a trivial detail and a simple enough thing for a synth owner to remedy (so long as the offline viewer is updated to read metadata.dzc when present).

And I do understand that the image URLs would need to be changed to relative URLs in metadata.dzc and 0.json in order for the official Photosynth 1 viewers to find what they need. 

I will be letting Photosynth 1 users on Get Satisfaction know of PhotosynthDownloader very soon and wanted to see if this small detail might be fixed before I did so.

Thank you for the reply.
