### ISSUE TITLE
When exporting a synth, comments on the synth should be fetched + stored.

### ISSUE THREAD

**Issue by natelawrence** [dddExperiments/PhotosynthDownloader#2]
I notice that when exporting synths with PhotosynthDownloader, comments do not appear to be fetched and stored in a comments.json file. 

Example: 
For GUID **67049f02-baf7-481f-b516-a47dc187a517**
Call: **http://photosynth.net/rest/2014-08/media/67049f02-baf7-481f-b516-a47dc187a517/comments?numRows=100&offset=0** and iterate offset until TotalResults have been downloaded.

Could you please add this?

**Comment by dddExperiments** [comment]
I didn't had a personal reason to save the comments but it was easy-ish to implement so I've just added :-)
See [latest commit](https://github.com/dddExperiments/PhotosynthDownloader/commit/6968ef07dc1c5215d11b7eccc5fb2fb16a2ed7aa).

**Comment by natelawrence** [comment]
Well, I thank you anyway. 

To my knowledge comments are saved in panos and synthpackets when officially exported, so this is good to have. 

I know that comments on Photosynth content was rare, but I think it is meaningful to those who received it (in most cases).
