### ISSUE TITLE
PhotosynthDownloader fails to download metadata_files/AppData/pscollection.bin

### ISSUE THREAD

**Issue by natelawrence** [dddExperiments/PhotosynthDownloader#3]
For every original synth, in addition to the deep zoom collection XML root and image pyramid folder hierarchy, there is an **AppData** folder which contains a binary file named **pscollection.bin**

I believe that this file contains the 2D layout information for clustering the photos together which matched each other. 

Could you update PhotosynthDownloader to also fetch this part of the Deep Zoom Collection for completeness? 

Thanks in advance.

**Comment by dddExperiments** [comment]
It would be nice to know what this file actually contains!
FYI the silverlight viewer is not fetching this file.
Also I assume that the grouping in the 2D layout is based on the coordinates system groups in 0.jon.

Implemented in [latest commit](https://github.com/dddExperiments/PhotosynthDownloader/commit/3f847825335fe0a55d440107769d5abc949c07b4) nonetheless.

**Comment by natelawrence** [comment]
As always, thank you for your patience.
