### ISSUE TITLE
PhotosynthDownloader neglects to download an original synth's synthcard thumbnail

### ISSUE THREAD

**Issue by natelawrence** [dddExperiments/PhotosynthDownloader#4]
From what I'm able to see, PhotosynthDownloader does not download an original synth's thumbnail URL used in its synth card on the user's profile or search results. 

Including this file would be greatly appreciated.

**Comment by dddExperiments** [comment]
Implemented in [latest commit](https://github.com/dddExperiments/PhotosynthDownloader/commit/3f847825335fe0a55d440107769d5abc949c07b4).

**Comment by natelawrence** [comment]
Thank you, Henri.
