### ISSUE TITLE
The root of /metadata.synth.bin

### ISSUE THREAD

**Issue by natelawrence** [dddExperiments/PhotosynthDownloader#5]
I'm not necessarily requesting that this be added to PhotosynthDownloader, but for completeness' sake it is worth noting that the root of /metadata.synth.bin is (to my knowledge) the same in every original synth and contains the following data: 

`<?xml version="1.0" encoding="UTF-8"?>`
`<SynthCollection/>`

I mention it, only because the official viewers might be looking for this information to read.

**Comment by dddExperiments** [comment]
Yes: I spotted that file while writing the [Photosynth1Webservice](https://github.com/dddExperiments/Photosynth1Webservice). This file doesn't contain any useful information (as you said it's the same for every synth) thus the Silverlight PS1 viewer is not requesting it.
