### ISSUE TITLE
Error messages: Error: connect ETIMEDOUT

### ISSUE THREAD

**Issue by natelawrence** [dddExperiments/PhotosynthDownloader#6]
I've seen error messages like these several times this evening: 

```
c:\PSD\app>node synth_downloader.js dcbc9c2d-c95f-4640-9a37-9a5408a82610 C:\PSD\NateLawrence
Downloading photosynth: dcbc9c2d-c95f-4640-9a37-9a5408a82610 to C:\PSD\NateLawrence
2 comments downloaded.
Downloading 167 images.
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 104.126.23.213:80
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)
```

```
c:\PSD\app>node synth_downloader.js facde222-8d12-409a-91e2-f95080b21a8b C:\PSD\Nathanael
Downloading photosynth: facde222-8d12-409a-91e2-f95080b21a8b to C:\PSD\Nathanael
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 157.55.211.99:443
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)
```

Is this a local problem on my machine?
...a limitation of my network?
...is the server throttling me temporarily?

Thanks for any insight you can offer, as this is stopping me from backing up my content.

**Comment by dddExperiments** [comment]
This is to be expected with a regular home internet connection.
**The downloader will resume automatically from where it stopped if you restart it**.
I'm planning to do a massive batch download later and will rent a cloud windows VM instance to avoid this issue personally.

But I've already managed to backup more than 50 very large PS1 from my home connection (and I had to resume the download for some of them).
