### ISSUE TITLE
GUID's alphabetical characters must be forced lowercase.

### ISSUE THREAD

**Issue by natelawrence** [dddExperiments/PhotosynthDownloader#7]
I discovered tonight that if a GUID's alpha characters are uppercase (as they used to be in URLs generated by the site - and therefore in people's old email or instant message archives where they might be copying URLs from) then PhotosynthDownloader will throw the following error: 

```
c:\PSD\app\ps1_downloader.js:380
                var num_coord_systems = root._num_coord_systems;
                                            ^

TypeError: Cannot read property '_num_coord_systems' of undefined
    at c:\PSD\app\ps1_downloader.js:380:31
    at IncomingMessage.<anonymous> (c:\PSD\app\downloadable_object.js:91:5)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```
If you could force the GUID to be lowercased before beginning processing, that would be ideal.
Thanks in advance.

**Comment by dddExperiments** [comment]
Implemented in [latest commit](https://github.com/dddExperiments/PhotosynthDownloader/commit/2a8336eb2f0586b722311f1919091c4f519879f1).
